#include <stdlib.h>

#include "Unity/unity.h"
#include "string_builder.h"

void test_sb_char_one_append(void) {
    string_builder_t* sb = sb_init();
    TEST_ASSERT_NOT_NULL(sb);

    int ret = sb_append_char(sb, 'A');
    TEST_ASSERT_EQUAL_INT(SB_NO_ERROR, ret);

    char* string = sb_to_string(sb);
    TEST_ASSERT_NOT_NULL(string);
    TEST_ASSERT_NOT_EMPTY(string);
    TEST_ASSERT_EQUAL_STRING("A", string);

    free(string);
    sb_free(sb);
}

void test_sb_char_two_appends(void) {
    string_builder_t* sb = sb_init();
    TEST_ASSERT_NOT_NULL(sb);

    int ret = sb_append_char(sb, 'A');
    TEST_ASSERT_EQUAL_INT(SB_NO_ERROR, ret);
    ret = sb_append_char(sb, 'B');
    TEST_ASSERT_EQUAL_INT(SB_NO_ERROR, ret);

    char* string = sb_to_string(sb);
    TEST_ASSERT_NOT_NULL(string);
    TEST_ASSERT_NOT_EMPTY(string);
    TEST_ASSERT_EQUAL_STRING("AB", string);

    free(string);
    sb_free(sb);
}

void test_sb_char_multiple_appends(void) {
    string_builder_t* sb = sb_init();
    TEST_ASSERT_NOT_NULL(sb);

    int ret = sb_append_char(sb, 'A');
    TEST_ASSERT_EQUAL_INT(SB_NO_ERROR, ret);
    ret = sb_append_char(sb, ' ');
    TEST_ASSERT_EQUAL_INT(SB_NO_ERROR, ret);
    ret = sb_append_char(sb, 'C');
    TEST_ASSERT_EQUAL_INT(SB_NO_ERROR, ret);
    ret = sb_append_char(sb, '!');
    TEST_ASSERT_EQUAL_INT(SB_NO_ERROR, ret);

    char* string = sb_to_string(sb);
    TEST_ASSERT_NOT_NULL(string);
    TEST_ASSERT_NOT_EMPTY(string);
    TEST_ASSERT_EQUAL_STRING("A C!", string);

    free(string);
    sb_free(sb);
}

void test_sb_char_max_appends(void) {
    string_builder_t* sb = sb_init();
    TEST_ASSERT_NOT_NULL(sb);

    const char ch = 'A';
    int ret, i;
    for (i = 0; i < SB_MAX_LENGTH; ++i) {
        ret = sb_append_char(sb, ch);
        TEST_ASSERT_EQUAL_INT(SB_NO_ERROR, ret);
    }

    char* string = sb_to_string(sb);
    TEST_ASSERT_NOT_NULL(string);
    TEST_ASSERT_NOT_EMPTY(string);
    TEST_ASSERT_EQUAL_STRING(
        "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
        "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
        "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
        "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
        "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
        "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
        "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
        "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
        "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
        "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
        "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
        "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
        "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
        "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
        "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
        "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",
        string
    );

    free(string);
    sb_free(sb);
}

void test_sb_char_more_than_max_appends(void) {
    string_builder_t* sb = sb_init();
    TEST_ASSERT_NOT_NULL(sb);

    const char ch = 'B';
    int ret, i;
    for (i = 0; i < SB_MAX_LENGTH; ++i) {
        ret = sb_append_char(sb, ch);
        TEST_ASSERT_EQUAL_INT(SB_NO_ERROR, ret);
    }

    ret = sb_append_char(sb, ch);
    TEST_ASSERT_EQUAL_INT(SB_ERROR, ret);

    char* string = sb_to_string(sb);
    TEST_ASSERT_NOT_NULL(string);
    TEST_ASSERT_NOT_EMPTY(string);
    TEST_ASSERT_EQUAL_STRING(
        "BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB"
        "BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB"
        "BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB"
        "BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB"
        "BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB"
        "BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB"
        "BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB"
        "BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB"
        "BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB"
        "BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB"
        "BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB"
        "BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB"
        "BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB"
        "BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB"
        "BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB"
        "BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB",
        string
    );

    free(string);

    sb_free(sb);
}
